package constants

const (
	CART_STATUS_AVAILABLE int64 = iota + 1
	CART_STATUS_INACTIVE
	CART_STATUS_PICKING
	CART_STATUS_PACKING
	CART_STATUS_WAITING_FOR_REPICK
	CART_STATUS_MOVING
	CART_STATUS_READY_MOVING
	CART_STATUS_TRANSFER_BIN
	CART_STATUS_PICKED
)

var CART_STATUS_NOT_AVAILABLE = []int64{2, 3, 4, 5, 6, 7, 8, 9}
