package constants

const (
	TOKEN_WMS     = "BUTLER_BOT_WMS_TOKEN"
	USER_ID_WMS   = "BUTLER_BOT_WMS_USER_ID"
	EMAIL_WMS     = "BUTLER_BOT_WMS_EMAIL"
	TOKEN_DISCORD = "BUTLER_BOT_DISCORD_TOKEN"
	WMS_DATA      = "WMS_DATA"
)
